[package]
name = "kiesraad-model"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
csv = { version = "1.3.1", optional = true }

[features]
chatty = []
validate = ["dep:csv"]
rand-validate = ["validate"]
